apiVersion: v1
kind: Service
metadata:
  name: actorsystem
  labels:
    name: actorsystem
spec:
  type: NodePort
  ports:
    - port: 8080
      name: http
  selector:
    app: actorsystem
---
apiVersion: v1
kind: Service
metadata:
  name: actorsystem-int
  labels:
    name: actorsystem
spec:
  clusterIP: None
  ports:
    - port: 8080
      name: http
    - port: 9090
      name: ea-cluster
  selector:
    app: actorsystem
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: actorsystem
spec:
  serviceName: "actorsystem-int"
  replicas: 1
  template:
    metadata:
      labels:
        app: actorsystem
    spec:
      volumes:
      - name: config
        configMap:
          name: actorsystem-config
          items:
          - key: config.yaml
            path: config.yaml
          - key: system.properties
            path: system.properties
      containers:
      - name: actorsystem
        image: elasticactors/actorsystem:latest
        imagePullPolicy: Always
        command: ["bash", "/opt/provision/configure_and_run.sh"]
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "PID=$(pidof java) && kill $PID && while ps -p $PID > /dev/null; do sleep 1; done"]
        env:
        - name: MAX_HEAP_SIZE
          value: "400M"
        - name: HEAP_NEWSIZE
          value: "100M"
        - name: NODE_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: ea-cluster
        volumeMounts:
        - mountPath: /etc/actorsystem/conf
          name: config